[workspace]
members = [
    "blocky",
    "blocky-net",
    "blocky-nbt",
    "blocky-derive",
    "blocky-protocol",
    "blocky-world",
    "blocky-auth",
    "blocky-client",
]
resolver = "2"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
