name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add clippy
      - run: cargo test --verbose

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
          rustup component add clippy
      - run: cargo clippy --verbose
